[3875][ADD] base_api_connection
qrtl/axls-oca pull request #132
Opened 2024-04-25 03:53 UTC by AungKoKoLin1997

[3875](https://www.quartile.co/web#id=3875&menu_id=505&cids=3&action=1457&model=project.task&view_type=form)

2024-04-26 05:41 UTC, yostashiro requested changes
As talked earlier, please create another bridge module `api_connection_key_encryption` (AGPL-3) to take care of the encryption/decription parts.

2024-04-26 08:08 UTC, yostashiro reviewed
Partial review.

2024-04-26 08:08 UTC, yostashiro commented on base_api_connection/models/api_call_mixin.py
> +        if not config:
```suggestion
        if not config:
            _logger.warning("No API config record found.")
```

2024-06-12 06:05 UTC, kanda999 commented on base_api_connection/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/qrtl/axls-private/issues>`_.
```suggestion
Bugs are tracked on `GitHub Issues <https://github.com/qrtl/axls-oca/issues>`_.
```
Can you please create the README file again?

2024-06-12 06:29 UTC, kanda999 approved these changes
Code and Functional review

2024-06-12 06:32 UTC, AungKoKoLin1997 commented
I change the readme file type from `.md` to `.rst` because generating readme manually doesn't recognize `.md`.

2024-06-12 07:45 UTC, yostashiro approved these changes
Just minor comments.

2024-06-12 07:45 UTC, yostashiro commented on base_api_connection/models/api_config.py
> +    code = fields.Char(required=True)
```suggestion
    code = fields.Char(required=True, help="Expected to act as an identifier of the API configuration record along with External System.")
```

2024-06-12 07:45 UTC, yostashiro commented on base_api_connection/readme/DESCRIPTION.rst
> +This module facilitates API connections between Odoo and other system. It is not usable on its own; rather, it is a low-level module intended to serve as a base for others. An example of such a modul
```suggestion
This module facilitates API connections between Odoo and other web services. It is not usable on its own; rather, it is a low-level module intended to serve as a base for others. An example of such a module is 'project_task_capture'.
```

2024-06-12 07:45 UTC, yostashiro commented on base_api_connection/models/api_config.py
> +            if duplicate_rec:
```suggestion
            existing_rec = self.search(
                [("code", "=", record.code), ("id", "!=", record.id)],
            )
            if existing_rec:
```

2024-06-13 03:10 UTC, merged