add-const module
qrtl/axls-oca pull request #37
Opened 2023-03-22 10:40 UTC by kanda999

2023-03-28 03:32 UTC, yostashiro approved these changes

2023-04-05 08:06 UTC, yostashiro requested changes
I think we should rename the module to stock_move_line_serial_unique to better represent what the module does.

2023-04-05 08:06 UTC, yostashiro commented on stock_quant_serial_unique/models/stock_move_line.py
> +    @api.constrains("lot_name", "lot_id")
Do we need to care about `lot_id`?

2023-04-05 08:06 UTC, yostashiro commented on stock_quant_serial_unique/models/stock_move_line.py
> +                message, dummy = quant._check_serial_number(
```suggestion
                message, dummy = self.env["stock.quant"]._check_serial_number(
```

2023-04-05 08:06 UTC, yostashiro commented on stock_quant_serial_unique/readme/DESCRIPTION.rst
> +duplicates.
```suggestion
This module adds a constraint on stock.move.line to make sure that no stock exists for the specified
serial 1) when serial is input (in lot_name field), and 2) when the lot is being created (in _action_done())
in purchase receipts, to avoid duplicates.
```

2023-04-05 08:06 UTC, yostashiro commented on stock_quant_serial_unique/models/stock_move_line.py
> +        to avoid duplicates.
```suggestion
        """This method intends ot check and make sure that the stock for specified serial does not exist.
        The check is expected to be triggered when:
        - user inputs serial (in lot_name) in purchase receipt / manufacturing order
        - serial record (stock.lot) is being created in _action_done()
```

2023-04-05 08:06 UTC, yostashiro commented on stock_quant_serial_unique/models/stock_move_line.py
> +                # Run this method when using option to create a new lot number.
```suggestion
                # Check should be done only in the scenario where new serial is created.
```

2023-04-05 08:06 UTC, yostashiro commented on stock_quant_serial_unique/models/stock_move_line.py
> +                if not record.lot_id:
```suggestion
                if not lot_id:
```

2023-04-05 08:24 UTC, AungKoKoLin1997 commented
The result of running test cases,
![Screenshot from 2023-04-05 14-52-42](https://user-images.githubusercontent.com/45355704/230024655-3118851d-5611-42ed-acbb-490c5ca7c1a4.png)

2023-04-05 13:55 UTC, yostashiro requested changes
@kanda999 Please write the tests in more concise and organized manner.  We should add more patterns, including those that should be processed with no error.

2023-04-05 13:55 UTC, yostashiro commented on stock_move_line_serial_unique/models/stock_move_line.py
> +        - serial record (stock.lot) is being created in _action_done()"""
```suggestion
        - serial record (stock.lot) is being created in _action_done()
        """
```

2023-04-05 13:55 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +            )
```suggestion
            )

```

2023-04-05 13:55 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        )
```suggestion
        vendor_location = self.env.ref("stock.stock_location_suppliers")
```
No need to start with `self.` if it's only used in the setup.

2023-04-05 13:55 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        )
```suggestion
```

2023-04-05 13:55 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +                "location_id": self.shelf1_location.id,
```suggestion
                "location_id": self.stock_location.id,
```

2023-04-05 13:55 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +                "location_dest_id": self.shelf1_location.id,
```suggestion
                "location_dest_id": self.stock_location.id,
```

2023-04-05 13:55 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        self.warehouse = self.env.ref("stock.warehouse0")
```suggestion
```
No need to define warehouse if it's only used to identify the company.

2023-04-06 07:50 UTC, kanda999 commented on stock_quant_serial_unique/models/stock_move_line.py
> +    @api.constrains("lot_name", "lot_id")
@yostashiro If lot_id is removed, it works well.

2023-04-06 09:23 UTC, yostashiro requested changes

2023-04-06 09:23 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        company = cls.env.ref("base.main_company")
```suggestion
```

2023-04-06 09:23 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +            {"company_id": company.id, "product_id": cls.product1.id, "name": "Lot1"}
```suggestion
            {"company_id": self.env.company.id, "product_id": cls.product1.id, "name": "Lot1"}
```

2023-04-06 09:23 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +    def _create_moveline(
Split this method into _create_picking( ) and _create_moveline(), or better yet, create pickings upfront in the setup for slightly better performance.

2023-04-06 09:23 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        )
This sort of obscures the business context.  What we should do are:
1. define the incoming picking type as `cls.picking_type_in = self.env.ref("stock.picking_type_in")` in the setup, and
2. do `self.assertEqual(self.picking_type_in.use_create_lots, True)` at the beginning of the first test that uses this picking type

Try to make the intentions of the test clear. Add comments as necessary.

2023-04-06 09:23 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        self.assertEqual(moveline.lot_name, "Lot2")
```suggestion
```
There is no point with this assertion. The point of the test is that Lot2 can be saved in incoming stock.move.line when there is no stock for the serial.  By the way, we should change the names to serial1 and serial2,  Lot1 and Lot2 are misleading when we are testing the serial cases.

2023-04-06 09:23 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        )
Same as above, define the picking type with `stock.picking_type_out` in the setup.

2023-04-06 09:23 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        )
The way this move line is created looks a bit random and, again, it obscures the business scenario being tested. If the stock is moved to the supplier location, that is a vendor return, but the picking type is selected randomly in the above step.

2023-04-06 09:23 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        self.assertEqual(moveline.lot_name, "Lot1")
```suggestion
```

2023-04-06 14:01 UTC, yostashiro requested changes
Hang in there. It's almost there. ;)

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        cls.owner1 = cls.env["res.partner"].create({"name": "Test Company"})
```suggestion
        cls.owner = cls.env["res.partner"].create({"name": "test owner"})
```

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        )
```suggestion
        cls.product = cls.env["product.product"].create(
            {"name": "test product", "type": "product", "tracking": "serial"}
        )
```
Avoid adding suffix to the variable when there is only one record.

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +                "name": "Serial1",
```suggestion
        serial1 = cls.env["stock.lot"].create(
            {
                "company_id": cls.env.company.id,
                "product_id": cls.product1.id,
                "name": "001",
```
Avoid applying the camel case in a random manner.

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        return self.env["stock.move.line"].create(move_line_data)
```suggestion
    def _create_moveline(self, picking, product):
        move_line_vals = {
            "picking_id": picking.id,
            "product_id": product.id,
            "qty_done": 1,
        }
        return self.env["stock.move.line"].create(move_line_vals)
```
As a convention, variable `xxx_id` should represent just ID, not a record.

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        return self.env["stock.picking"].create(picking_data)
```suggestion
    def _create_picking(self, picking_type, location, location_dest, owner):
        picking_vals = {
            "picking_type_id": picking_type.id,
            "location_id": location.id,
            "location_dest_id": location_dest.id,
            "owner_id": owner.id,
        }
        return self.env["stock.picking"].create(picking_vals)
```

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        picking = self._create_picking(
```suggestion
        picking_in = self._create_picking(
```
Make the intention of the test clearer in one way or another where you can.

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        self.assertEqual(self.picking_type_in.use_create_lots, True)
```suggestion
```
No need to repeat this check.  This is done in the previous test.

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +    def test_stock_quant_serial_unique_with_duplicate_serial(self):
```suggestion
    def test_duplicate_serial(self):
```
Remove the string that carries little meaning.

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        moveline.write({"lot_name": "Serial2"})
```suggestion
        moveline.write({"lot_name": "002"})
        picking_in.action_confirm()
        picking_in.button_validate()
```
Test until the end of the picking process.

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        moveline.write({"lot_name": "Serial1"})
```suggestion
        moveline.write({"lot_name": "001"})
        picking_out.action_confirm()
        picking_out.button_validate()
```

2023-04-06 14:01 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
Add another incoming test case where:
1. move line is created with serial name 002
2. quant is created for serial name 002
3. button_validate, and the validation error is thrown

2023-04-07 02:58 UTC, yostashiro requested changes
Try and improve the test method names.

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        picking_val = {
```suggestion
        picking_vals = {
```
As a convention.

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        move_line_val = {
```suggestion
        move_line_vals = {
```

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        with self.assertRaises(ValidationError):
```suggestion
        # Stock exists for serial '001'.
        with self.assertRaises(ValidationError):
```

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        moveline.write({"lot_name": "002"})
```suggestion
        # Stock does not exist for serial '002'.
        moveline.write({"lot_name": "002"})
```

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        )
Move this to the setup.

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +            picking_in.action_confirm()
```suggestion
        picking_in.action_confirm()
        with self.assertRaises(ValidationError):
```
To be specific with the step where the error is thrown.

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        picking_in.action_confirm()
```suggestion
```

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        with self.assertRaises(ValidationError):
```suggestion
        # Now stock exists for serial '002'.
        with self.assertRaises(ValidationError):
```

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        moveline.write({"lot_name": "003"})
```suggestion
        # Stock does not exist for serial '003'.
        moveline.write({"lot_name": "003"})
```

2023-04-07 02:58 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        moveline.write({"lot_id": self.serial1.id})
```suggestion
        # Stock exists for serial '001' but no check should be done for outgoing/internal moves.
        moveline.write({"lot_id": self.serial1.id})
```

2023-04-07 03:34 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +        cls.env["stock.quant"].create(
```suggestion
        # Create stock for serial '001'.
        cls.env["stock.quant"].create(
```

2023-04-07 03:34 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +    def test_duplicate_serial_with_existing_serial(self):
```suggestion
    def test_picking_in_serial_with_stock(self):
```

2023-04-07 03:34 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +    def test_create_new_serial_and_check_deplicates(self):
```suggestion
    def test_picking_in_serials_with_and_without_stock(self):
```

2023-04-07 03:34 UTC, yostashiro commented on stock_move_line_serial_unique/tests/test_stock_move_line_serial_unique.py
> +    def test_picking_type_out_with_existing_serial(self):
```suggestion
    def test_picking_out_serial_with_stock(self):
```

2023-04-07 04:11 UTC, yostashiro approved these changes
👍

2023-04-10 05:49 UTC, merged