[3454][ADD] purchase_reception_status
qrtl/axls-oca pull request #58
Opened 2023-05-22 09:20 UTC by rinaldifirdaus

[3454](https://www.quartile.co/web#id=3454&action=771&model=project.task&view_type=form&menu_id=505)

2023-05-22 09:22 UTC, rinaldifirdaus commented
This module is extended from the original OCA Repo by adjust receipt_status to be invisible.
will update this module with the original one once its being merged and added the adjustment to hid the receipt_status.

2023-05-22 09:27 UTC, yostashiro requested changes
Please add another commit with your changes on top of the OCA PR content, so that it will be easy to identify your changes later.

2023-05-22 09:27 UTC, yostashiro commented on purchase_reception_status/views/purchase_order.xml
> +            </xpath>
Move this to above record and remove this record.

2023-05-25 14:49 UTC, yostashiro commented
> Please add another commit with your changes on top of the OCA PR content, so that it will be easy to identify your changes later.

@rinaldifirdaus Commit history currently doesn't reflect my request.  The commits we should have here are:

1. A commit that mirrors the content of the OCA PR.
2. Another commit with your changes.

2023-05-29 07:28 UTC, rinaldifirdaus commented
> @rinaldifirdaus Commit history currently doesn't reflect my request. The commits we should have here are:
> 1. A commit that mirrors the content of the OCA PR.
> 2. Another commit with your changes.

@yostashiro san, I've just added the new commits as above suggestions.
kindly your review. thank you

2023-05-29 10:47 UTC, yostashiro approved these changes

2023-05-30 02:09 UTC, rinaldifirdaus commented
Commit squashed

2023-06-06 06:43 UTC, merged