[3326][IMP] base_custom_filter
qrtl/axls-oca pull request #62
Opened 2023-06-05 04:25 UTC by AungKoKoLin1997

[3326](https://www.quartile.co/web#id=3326&action=771&model=project.task&view_type=form&menu_id=505)

2023-06-06 15:21 UTC, yostashiro requested changes
Can you please add simple tests and update readme as well.

2023-06-06 15:21 UTC, yostashiro commented on base_custom_filter/models/ir_filters.py
> +            ("search", "Standard Search"),
Shouldn't this be inserted in between `favorite` and `filter`?

2023-06-06 15:21 UTC, yostashiro commented on base_custom_filter/views/ir_filters_views.xml
> +                >{'invisible': [('type', '=', 'groupby')], 'required': [('type','!=', 'search')]}</attribute>
I don't understand why this change is needed.

2023-06-06 15:21 UTC, yostashiro commented on base_custom_filter/views/ir_filters_views.xml
> +                    attrs="{'invisible': [('type', '!=', 'search')]}"
It makes the design incoherent if we limit this field only to `search`. Make it available to `filter` and `groupby`, and adjust `get_view()` accordingly.

2023-06-06 15:21 UTC, yostashiro commented on base_custom_filter/views/ir_filters_views.xml
>                      name="group_id"
There is no point showing this field when type is `search`.

2023-06-06 15:21 UTC, yostashiro commented on base_custom_filter/models/ir_filters.py
> +    filter_domain = fields.Text()
Would be nice to have a help text with a simple example.

2023-06-06 15:21 UTC, yostashiro commented on base_custom_filter/models/base.py
> +            if any(group in group_ids for group in search_field_group_ids) or not search_field_group_ids:
Create a method for this part.
```python
    @api.model
    def _user_has_access_to_item(self, item):
        if not item.group_ids:
            return True
        return bool(set(self.env.user.groups_id.ids) & set(item.group_ids.ids))
```

And then call it like this.

```suggestion
            if not self._user_has_access_to_item(search_field):
                continue
```

Apply this to relevant parts of other methods.

2023-06-07 01:10 UTC, yostashiro commented on base_custom_filter/views/ir_filters_views.xml
> +                />
Should be hidden for type `favorite`.

2023-06-07 01:10 UTC, yostashiro commented on base_custom_filter/models/ir_filters.py
> +                                )
Fix the styling and avoid a long explanation. The audience should already know the concept of the filter domain. IMO, something like the following would be sufficient.

```
help="Enter a filter domain expression if necessary. Example: [('default_code', 'ilike', self)]"
```

2023-06-07 03:55 UTC, yostashiro requested changes

2023-06-07 03:55 UTC, yostashiro commented on base_custom_filter/readme/CONFIGURE.rst
> +   * The **User Groups** that will be applied to the search for the visibility of users.
Can you re-organize the content by type here? It's now confusing as a type only uses certain set of fields.

2023-06-12 03:04 UTC, rinaldifirdaus commented
Functional test: 
add following custom filter, search result works fine!
<img width="751" alt="image" src="https://github.com/qrtl/axls-oca/assets/122415281/6eb23725-0e69-4b74-9a16-82df693a2185">

2023-06-12 07:37 UTC, yostashiro requested changes
@AungKoKoLin1997 Please go ahead and create a PR in the OCA repo so that the community knows what's happening.

2023-06-12 07:37 UTC, yostashiro commented on base_custom_filter/models/base.py
> +
```suggestion
```

2023-06-12 07:37 UTC, yostashiro commented on base_custom_filter/readme/DESCRIPTION.rst
>  filters and group by menus of a model's search view.
Refine the sentence. It currently looks a bit broken.

2023-06-12 07:37 UTC, yostashiro commented on base_custom_filter/tests/test_filters.py
>      def setUpClass(cls, chart_template_ref=None):
```suggestion
    def setUpClass(cls):
```

2023-06-12 07:37 UTC, yostashiro commented on base_custom_filter/tests/test_filters.py
> +        filters_group = Form(filters_obj)
Why `filters_group`?  I think this variable name is misleading.  `filter_form` would be more appropriate.

2023-06-12 07:37 UTC, yostashiro commented on base_custom_filter/tests/test_filters.py
I find these tests a bit random (e.g. the test name is test_sale_order_line() when it has nothing to do with sale order line) and of little value.

Can you add some patterns to check the content of the value returned from `get_view()`.

2023-06-12 07:37 UTC, yostashiro commented on base_custom_filter/models/ir_filters.py
> +            ("search", "Standard Search"),
What does this `Standard` mean, by the way?

2023-06-12 07:37 UTC, yostashiro commented on base_custom_filter/readme/CONFIGURE.rst
> +      * The **User Groups** that will be applied to the groupby for the visibility of users.
```suggestion
#. Create a record assiging model, type (search/filter/groupby) and necessary attributes.
    Available fields and corresponding attributes (in brackets) for each type are as follows:

   Search:

      * Search Field (``name``)
      * Filter Domain (``filter_domain``)
      * Domain (``domain``)
      * User Groups (``groups``)

   Filter:

      * Domain (``domain``)
      * User Groups (``groups``)

   Group By:

      * Group By Field (field to be assigned to ``group_by`` context)
      * User Groups (``groups``)

   See `the official documentation <https://www.odoo.com/documentation/16.0/developer/reference/backend/views.html#search>`_ for the definition of each attribute.

   Additionally, filter and group-by records can be respectively grouped together with
   "Group" assignment (there will be a separator in between groups).
``

2023-06-15 15:18 UTC, yostashiro reviewed
Thanks for the update, Lin.

2023-06-15 15:18 UTC, yostashiro commented on base_custom_filter/views/ir_filters_views.xml
>                      name="group_id"
Please take care of this point.

2023-06-15 15:18 UTC, yostashiro commented on base_custom_filter/tests/test_filters.py
@AungKoKoLin1997 Can you please follow up on the following:

- Normalize the setup and tests - prepare variables in the setup and user them in tests.
- Split test_base_custom_filter() into smaller pieces as it's currently a bit bloated. We may prepare one test per type, for example.

2023-06-15 15:18 UTC, yostashiro commented on base_custom_filter/tests/test_filters.py
> +        filters_form = filters_form.save()
I'd prefer not to have these lines unless it's for the purpose of a "setup", which is currently not the case. IMO, there is no point adding another pattern to confirm that the form can be saved.

2023-06-16 07:55 UTC, yostashiro commented on base_custom_filter/tests/test_filters.py
> +            filters_group.type = "search"
@AungKoKoLin1997 This pattern shouldn't exist according to your last update...

2023-06-16 09:34 UTC, yostashiro commented on base_custom_filter/tests/test_filters.py
> +        filter_group.unlink()
What is this `unlink()` for?

2023-06-16 09:37 UTC, yostashiro approved these changes

2023-06-20 08:13 UTC, kanda999 approved these changes

2023-06-20 08:15 UTC, merged