[3494][ADD] purchase_order_payment_term
qrtl/axls-oca pull request #79
Opened 2023-07-30 15:39 UTC by rinaldifirdaus

[3494](https://www.quartile.co/web#id=3494&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2023-07-31 02:55 UTC, yostashiro requested changes
@rinaldifirdaus As we just talked, please make the adjustment on RFQ print as well.

2023-07-31 02:55 UTC, yostashiro commented on purchase_order_payment_term/__manifest__.py
> +    "depends": ["base", "purchase"],
```suggestion
    "depends": ["purchase"],
```

2023-07-31 02:55 UTC, yostashiro commented on purchase_order_payment_term/__manifest__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
```suggestion
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
```
Please do the same for all headers.

2023-07-31 02:55 UTC, yostashiro commented on purchase_order_payment_term/__manifest__.py
> +    "website": "https://github.com/OCA/purchase-workflow",
```suggestion
    "website": "https://github.com/OCA/purchase-reporting",
```

2023-07-31 03:00 UTC, yostashiro commented
@rinaldifirdaus I suggested a different name in https://github.com/qrtl/axls-custom/pull/38#pullrequestreview-1550040028, so please provide a reason in case you'd like to use a different name.

2023-07-31 04:03 UTC, yostashiro approved these changes
LGTM 👍 

Please follow up to create a PR in the OCA repo.

2023-08-08 07:32 UTC, kanda999 approved these changes

2023-08-08 07:32 UTC, merged