[3494][ADD] purchase_order_line_sequence, stock_picking_line_sequence
qrtl/axls-oca pull request #81
Opened 2023-08-01 11:34 UTC by rinaldifirdaus

[3494](https://www.quartile.co/web#id=3494&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2023-08-03 04:24 UTC, rinaldifirdaus commented
previously i found issue that some of the translation of purchase_order_line_sequence wass not applied on the database.
But it can be resolve by do the following:
1. Go to settings>translations>import translation
2. set language name, code, upload ja.po file, overwrite existing terms.

2023-08-08 07:30 UTC, kanda999 requested changes
Please update.

2023-08-08 07:30 UTC, kanda999 commented on purchase_order_line_sequence/i18n/ja.po
> +msgstr "非表化示シーケンス"
```suggestion
msgstr "非表示シーケンス"
```

2023-08-08 08:03 UTC, kanda999 approved these changes

2023-08-08 08:04 UTC, merged